Major cleanup, formatting, code, etc.
improve spacing and comments  
change .temp to .tmp  
replace backticks with $()  
improve echo message  
fix AOK mirrorlist comment appearing below AOK mirrors  
create backup of original mirrorlist  
changed main menu text

diff --git a/aok b/aok
--- a/aok
+++ b/aok
@@ -1,14 +1,22 @@
 #!/bin/bash -e
 
-## This script depends on files in the directory "/home/chronos/user/Downloads/aok-master"
+## This script depends on files in the directory:
+## "/home/chronos/user/Downloads/aok-master"
 ## Or at least files in the directory "/usr/local/aok"
 
+## Developer Note: curl is built without metalink support in Chrome OS,
+## so the curl commands used here do not require metalink support
+
+## Check tools and copy files
 tools_check () {
 echo "Checking tools..."
+
+## Check if run with sudo or as root
 if [ "$EUID" != 0 ]; then
   echo "Root privilege not found, quitting."
   exit 1
 fi
+
 ## Copy aok files. Remove outdated ones if necessary.
 if [ -d "/home/chronos/user/Downloads/aok-master" ]; then
   if [ -d "/usr/local/aok" ]; then
@@ -22,78 +30,98 @@ if [ -d "/home/chronos/user/Downloads/aok-master" ]; then
   fi
   cp -r /home/chronos/user/Downloads/aok-master/. /usr/local/aok
 fi
+
+## Change directory to /usr/local/aok for the rest of the script
 cd /usr/local/aok
+
 ## Check for vboot-utils and more
 crossystem hwid && echo || echo "crossystem not found. OK."
-curl -V > /dev/null || { echo "curl not found. exiting."; exit 1; }
+curl -V > /dev/null || { echo "curl not found. exiting." ; exit 1; }
 ping -c 1 archlinuxarm.org > /dev/null \
   || echo "archlinuxarm.org not found. May use local data."
-md5sum --version > /dev/null || { echo "md5sum not found. exiting."; exit 1; }
-umount -V > /dev/null || { echo "umount not found. exiting."; exit 1; }
+md5sum --version > /dev/null || { echo "md5sum not found. exiting." ; exit 1; }
+umount -V > /dev/null || { echo "umount not found. exiting." ; exit 1; }
 fdisk -V
-cgpt add -h > /dev/null || { echo "cgpt not found. exiting."; exit 1; }
-mkfs -V > /dev/null || { echo "mkfs not found. exiting."; exit 1; }
-dd --version > /dev/null || { echo "dd not found. exiting."; exit 1; }
+cgpt add -h > /dev/null || { echo "cgpt not found. exiting." ; exit 1; }
+mkfs -V > /dev/null || { echo "mkfs not found. exiting." ; exit 1; }
+dd --version > /dev/null || { echo "dd not found. exiting." ; exit 1; }
+
 echo "Tools check complete."
 }
+
 
 ## Test mirrors and hopefully create bestmirrors.txt
 test_mirrors () {
 echo "Testing mirrors..."
+
 ## Create or reset the working mirrors list file, and set local mirror status
-echo -n > workingmirrors.txt.temp
+echo -n > workingmirrors.txt.tmp
 LOCAL_MIRROR_SUCCESS=false
-## All local Arch Linux ARM mirrors, not the main load-balancing mirror
-## This is the list from https://archlinuxarm.org/about/mirrors
-## Plus the list provided in /etc/pacman.d/mirrorlist
+
+## All local Arch Linux ARM mirrors, not the main load-balancing mirror:
+## https://archlinuxarm.org/about/mirrors
+## /etc/pacman.d/mirrorlist
 all_Mirrors=(au br2 dk de3 de de4 de5 de6 eu gr hu nl ru sg za tw ca.us nj.us fl.us il.us vn)
+
 ## Try to download md5 file for each mirror, recording speeds
 for SUBDOMAIN in ${all_Mirrors[@]}; do
+
   ## Download md5, and save Current Speed from curl progress meter
   ## A higher number is better. Domains that fail will have a null value.
-  CURRENT_SPEED=`curl --max-time 5 -LO \
+  CURRENT_SPEED=$(curl --max-time 5 -LO \
   ${SUBDOMAIN}.mirror.archlinuxarm.org/os/ArchLinuxARM-armv7-chromebook-latest.tar.gz.md5 \
-  2>&1 | grep $'\r100' | grep -o '[^ ]*$' || echo -n`
+  2>&1 | grep $'\r100' | grep -o '[^ ]*$' || echo -n)
+
   ## What if it's a bad md5 file, like a 404?
   ## It should contain the filename, and be only 1 line
-  if [ `grep ArchLinuxARM-armv7-chromebook-latest.tar.gz \
-      ArchLinuxARM-armv7-chromebook-latest.tar.gz.md5 | wc -l` -eq 1 ]; then
+  if [ $(grep ArchLinuxARM-armv7-chromebook-latest.tar.gz \
+      ArchLinuxARM-armv7-chromebook-latest.tar.gz.md5 | wc -l) -eq 1 ]; then
+
     ## Save the working mirror to a text file, Format: Speed (tab) Mirror
     if [ -n "$CURRENT_SPEED" ]; then
       echo -e "${CURRENT_SPEED}\t${SUBDOMAIN}.mirror.archlinuxarm.org" \
-        | tee -a workingmirrors.txt.temp
-      ## Save the best md5
+        | tee -a workingmirrors.txt.tmp
+      ## Save the best md5, and record success
       cp -u ArchLinuxARM-armv7-chromebook-latest.tar.gz.md5 \
-          ArchLinuxARM-armv7-chromebook-latest.tar.gz.md5.temp
+          ArchLinuxARM-armv7-chromebook-latest.tar.gz.md5.tmp
       MIRROR_SUCCESS=true
       LOCAL_MIRROR_SUCCESS=true
+
+    ## If the md5 download failed, just report that.
     else
       echo -e "\t${SUBDOMAIN}.mirror.archlinuxarm.org failed completely"
     fi
+
+  ## The md5 file appears to be invalid, so restore the good one if possible. 
   else
     echo -e "\t${SUBDOMAIN}.mirror.archlinuxarm.org did not provide the correct file (Likely 404)"
     ## Restore the real (and best) md5 if one exists
-    cp ArchLinuxARM-armv7-chromebook-latest.tar.gz.md5.temp \
+    cp ArchLinuxARM-armv7-chromebook-latest.tar.gz.md5.tmp \
         ArchLinuxARM-armv7-chromebook-latest.tar.gz.md5 || echo -n
   fi
 done
+
+## Create bestmirors.txt if possible
 if [ "$LOCAL_MIRROR_SUCCESS" = true ]; then
   echo
   echo "These are your current best mirrors:"
   echo -e "SPEED\tMIRROR"
-
   ## Sort human readable reverse (highest first) to a sorted file
-  cat workingmirrors.txt.temp | sort -hr | tee bestmirrors.txt
+  cat workingmirrors.txt.tmp | sort -hr | tee bestmirrors.txt
 else
   echo
   echo "No working local mirrors found."
 fi
+
 ## Cleanup
-rm -f ArchLinuxARM-armv7-chromebook-latest.tar.gz.md5.temp
-rm -f workingmirrors.txt.temp
+rm -f ArchLinuxARM-armv7-chromebook-latest.tar.gz.md5.tmp
+rm -f workingmirrors.txt.tmp
 echo "Mirrors testing complete."
-echo "Do NOT click on Chrome OS pop-up messages when they appear!"
+
+## Add a message just before a likely pause period
+echo "Do NOT click on pop-up messages!"
 }
+
 
 ## Offline function, try using local md5 or quit
 use_local_md5 () {
@@ -105,22 +133,29 @@ use_local_md5 () {
   fi
 }
 
+
+## Installation process. Already working in /usr/local/ok
 install_arch () {
+
 echo "Preparing files..."
 mkdir -p distro
 cd distro
-## Check if Internet and DNS is working before trying every mirror
-## curl is built without metalink support in Chrome OS.
-## it's a small file, so be impatient
 MIRROR_SUCCESS=false
+
+## Check if Internet and DNS are working before testing any mirror
 if ping -c 1 archlinuxarm.org > /dev/null; then
+
+  ## Allow 10 seconds to download the md5 from main mirror
   curl --max-time 10 -LO \
       mirror.archlinuxarm.org/os/ArchLinuxARM-armv7-chromebook-latest.tar.gz.md5 && {
-        cp -u ArchLinuxARM-armv7-chromebook-latest.tar.gz.md5 \
-            ArchLinuxARM-armv7-chromebook-latest.tar.gz.md5.temp
-        MIRROR_SUCCESS=true
-      } || echo -n
+    cp -u ArchLinuxARM-armv7-chromebook-latest.tar.gz.md5 \
+        ArchLinuxARM-armv7-chromebook-latest.tar.gz.md5.tmp
+    MIRROR_SUCCESS=true
+  } || echo -n
+
+  ## Now test local mirrors
   test_mirrors
+
   if [ "$MIRROR_SUCCESS" = false ]; then
     echo "Cannot download latest md5: all mirrors failed."
     use_local_md5
@@ -129,16 +164,20 @@ else
     echo "Cannot download latest md5: archlinuxarm.org not found."
     use_local_md5
 fi
-## Check even if it doesn't exist, or try downloading
+
+## Check md5 against file even if it doesn't exist, or try downloading
 md5sum -c ArchLinuxARM-armv7-chromebook-latest.tar.gz.md5 --status || {
   echo "Attempting download..."
   if ping -c 1 archlinuxarm.org > /dev/null; then
-    ## Here's where to use the fastest mirror from testing
+
+    ## Get ready to try downloading from every working local mirror
     DOWNLOADED=false
     DL=1
-    MAX_MIRRORS=`cat bestmirrors.txt | wc -l`
+    MAX_MIRRORS=$(cat bestmirrors.txt | wc -l)
+
+    ## Here's where to use the fastest mirror from testing
     while [ "$DL" -le "$MAX_MIRRORS" ]; do
-      TRY_MIRROR=`sed -n "${DL}p" bestmirrors.txt | sed $'s/.*\t//'`
+      TRY_MIRROR=$(sed -n "${DL}p" bestmirrors.txt | sed $'s/.*\t//')
       curl -LO ${TRY_MIRROR}/os/ArchLinuxARM-armv7-chromebook-latest.tar.gz \
           && {
             DOWNLOADED=true
@@ -146,35 +185,53 @@ md5sum -c ArchLinuxARM-armv7-chromebook-latest.tar.gz.md5 --status || {
           } ||
           DL=$[$DL+1]
     done
+
+    ## Try the main load-balanced mirror as a last resort
     if [ "$DOWNLOADED" = false ]; then
-      ## Try the main load-balanced mirror as a last resort
       curl -LO mirror.archlinuxarm.org/os/ArchLinuxARM-armv7-chromebook-latest.tar.gz \
-        || {
-          echo "Couldn't download Arch Linux. Check your Internet connection reliability."
-          exit 1
-        }
+          || {
+        echo "Couldn't download Arch Linux. Check your Internet connection reliability."
+        exit 1
+      }
     fi
+
+    ## Final md5 test after any downloads
     echo "Download complete."
     md5sum -c ArchLinuxARM-armv7-chromebook-latest.tar.gz.md5 || {
       echo "The Arch Linux download was corrupted. You may want to try again."
       exit 1
     }
+
+  ## No ping response from archlinuxarm.org
   else
-    echo "Arch Linux local copy unavailable. Can't download: Not online. Exiting."
+    echo "Arch Linux local copy unavailable."
+    echo "No ping response from archlinuxarm.org. Exiting."
     exit 1
   fi
 }
+
+## Return to aok from aok/distro
 cd -
+
 echo "File preparation complete."
-## Now that everything is ready, truly get started
+
+
+## Tools and files exist. Start installation.
 echo "Starting Arch Linux Installation..."
 umount ${DEVICE}* 2> /dev/null || echo -n
 
-## Automate fdisk. I know sgdisk is preferred for scripting, but
-## This is done so you can understand it, learn from it, and use
-## it yourself if you want to.
-## Do not change the whitespace here, it is very important
-## passing "y" in case it asks if sure. harmless if not asked.
+## Automate fdisk.
+## Normally sgdisk is preferred for scripting, but documentation is scarce.
+## This method is easier to understand, modify, and use as needed.
+
+## Do not change the whitespace here, it is very important.
+## Each blank line represents accepting the default by just pressing enter.
+## Passing "y" in case it asks about signatures. Harmless if not asked.
+## The GUID used is for "ChromeOS kernel", which may be menu option 65 or 64 or
+## something else, depending on what version of fdisk is being used.
+
+## You may want to add a secondary kernel partition (and also copy the kernel)
+## You may also want to add a swap drive (and enable swap)
 { fdisk ${DEVICE} << "END"
 g
 n
@@ -207,13 +264,13 @@ umount ${DEVICE}* 2> /dev/null || echo -n
 umount rootfs 2> /dev/null || echo -n
 
 ## Make filesystem
-## Avoid mkfs complaining that it's 'apparently in use by the system' but isn't (-F -F)
+## Avoid mkfs complaining that it's 'apparently in use by the system' but isn't
 mkfs.ext4 -F -F ${DEVICE}${PARTITION_2}
 
 ## Updating partition info, regardless of whether it's necessary or not
 partx -u ${DEVICE}
 
-## Copy files
+## Copy files. Current directory is aok. Creating aok/rootfs for mounting
 mkdir -p rootfs
 mount ${DEVICE}${PARTITION_2} rootfs
 echo "Copying Filesystem..."
@@ -235,18 +292,23 @@ echo "kernel.printk = 3 3 3 3" >> rootfs/etc/sysctl.d/20-quiet-printk.conf
 ## Add best mirrors to pacman mirrorlist
 if [ -f distro/bestmirrors.txt ]; then
   ADD=1
-  MAX_MIRRORS=`cat distro/bestmirrors.txt | wc -l`
-  echo >> rootfs/etc/pacman.d/mirrorlist
+  MAX_MIRRORS=$(cat distro/bestmirrors.txt | wc -l)
+  echo > usemirrors.txt
   echo "## Automatically added mirrors from AOK mirror testing" \
-      >> rootfs/etc/pacman.d/mirrorlist
+      >> usemirrors.txt
+
+  ## Reformat and add each working mirror to use list
   while [ "$ADD" -le "$MAX_MIRRORS" ]; do
-    APPEND=`sed -n "${ADD}p" distro/bestmirrors.txt | sed $'s/.*\t//'`
+    APPEND=$(sed -n "${ADD}p" distro/bestmirrors.txt | sed $'s/.*\t//')
     echo 'Server = http://'${APPEND}'/$arch/$repo' \
         >> usemirrors.txt
     ADD=$[$ADD+1]
   done
-  ## append those mirrors to the TOP of the mirrorlist
-  cat usemirrors.txt rootfs/etc/pacman.d/mirrorlist > temp && mv temp rootfs/etc/pacman.d/mirrorlist
+
+  ## Append use mirror list to the TOP of the mirrorlist
+  cp rootfs/etc/pacman.d/mirrorlist rootfs/etc/pacman.d/mirrorlist.bak
+  cat usemirrors.txt rootfs/etc/pacman.d/mirrorlist > newmirrorlist.tmp \
+      && mv newmirrorlist.tmp rootfs/etc/pacman.d/mirrorlist
 fi
 
 ## Bulk copy of custom content (will ALSO install in specific places)
@@ -267,7 +329,7 @@ cp -r extra rootfs/usr/local/aok
 chmod +x rootfs/usr/local/aok/extra/dim
 chmod +x rootfs/usr/local/aok/extra/*.sh
 
-## ALSO, copy files to specific locations
+## ALSO, copy global configuration files to specific locations
 
 ## Copy quiet background for Xfce
 mkdir -p rootfs/usr/share/backgrounds/xfce
@@ -286,7 +348,7 @@ cp files/linux_archlinux_os_blue_black_logo_30861_1366x768.jpg rootfs/usr/share/
 mkdir -p rootfs/etc/lightdm
 cp files/lightdm-gtk-greeter.conf rootfs/etc/lightdm
 
-## ALSO, Copy Global Xfce pre-configs
+## ALSO, copy Xfce skeleton files
 
 ## Copy desktop, panel, power settings
 mkdir -p rootfs/etc/skel/.config/xfce4/xfconf/xfce-perchannel-xml
@@ -309,10 +371,13 @@ Welcome. To finish installing AOK, do the following:
 2. After logging in, type "setup" and press enter.
 
 EOF
+
 ## Finish up
 umount rootfs
 sync
 rmdir rootfs
+
+## Post-installation menus
 echo
 echo "Arch Linux Installation is complete."
 echo
@@ -335,9 +400,9 @@ case "$FUTURE" in
 esac
 echo "Done."
 echo
-echo "To boot from USB on a Samsung XE303C12, make sure the USB drive is in the black USB 2.0 Port"
+echo "To boot from USB on a Samsung XE303C12, use the USB 2.0 Port"
 echo
-echo "Reboot and press CTRL-U to boot USB or SD Card, or CTRL-D to boot Internal Storage."
+echo "Reboot and press CTRL-U to boot USB/SD, or CTRL-D to boot Internal Storage."
 echo
 echo "Would you like to reboot now? (Y/n)"
 read -p "> " REBOOT
@@ -350,16 +415,18 @@ case "$REBOOT" in
       ;;
 esac
 }
+## End of install_arch function
 
+## Script starts here
 lsblk
 echo
-echo "Select the device where you would like to install Arch Linux:"
+echo "Select what to erase and install Arch Linux on:"
 echo 
-echo "0) Laptop (/dev/mmcblk0). Do not run this from ChromeOS"
-echo "1) SD Card (/dev/mmcblk1)"
-echo "a) USB Stick (/dev/sda). Some USB Sticks work, some don't"
-echo "b) Second USB Stick or VirtualBox SD Card (/dev/sdb)"
-echo "q) Quit without making changes"
+echo "0) eMMC, erase ChromeOS  /dev/mmcblk0  Must be running from SD/USB already"
+echo "1) SD Card               /dev/mmcblk1  4GB+ needed"
+echo "a) USB Drive             /dev/sda      4GB+ needed. For compatible USB's."
+echo "b) Second USB Drive      /dev/sdb      or VirtualBox SD Card"
+echo "q) Quit"
 echo
 read -p "> " CHOICE
 case "$CHOICE" in
