removed unnecessary function calls
it's a lot more chronological this way

diff --git a/aok b/aok
--- a/aok
+++ b/aok
@@ -7,8 +7,67 @@
 ## Developer Note: curl is built without metalink support in Chrome OS,
 ## so the curl commands used here do not require metalink support
 
+## Script starts here
+lsblk
+
+if [ $(uname -p | grep ARMv7) ]; then
+  echo
+  echo "Select what to ERASE and install Arch Linux on:"
+  echo 
+  echo "0) eMMC, erase ChromeOS  /dev/mmcblk0  Must be running from SD/USB already"
+  echo "1) SD Card               /dev/mmcblk1  4GB+ needed"
+  echo "a) USB Drive             /dev/sda      4GB+ needed. For compatible USB's."
+  echo "b) Second USB Drive      /dev/sdb      or VirtualBox SD Card"
+  echo "q) Quit"
+  echo
+else
+  echo
+  echo "Select what to ERASE and install Arch Linux on:"
+  echo 
+  echo "0) /dev/mmcblk0"
+  echo "1) /dev/mmcblk1"
+  echo "a) /dev/sda"
+  echo "b) /dev/sdb"
+  echo "c) /dev/sdc"
+  echo "q) Quit"
+  echo
+fi
+
+read -p "> " CHOICE
+case "$CHOICE" in
+  0)
+    DEVICE='/dev/mmcblk0'
+    PARTITION_1='p1'
+    PARTITION_2='p2'
+    ;;
+  1)
+    DEVICE='/dev/mmcblk1'
+    PARTITION_1='p1'
+    PARTITION_2='p2'
+    ;;
+  a)
+    DEVICE='/dev/sda'
+    PARTITION_1='1'
+    PARTITION_2='2'
+    ;;
+  b)
+    DEVICE='/dev/sdb'
+    PARTITION_1='1'
+    PARTITION_2='2'
+    ;;
+  c)
+    DEVICE='/dev/sdc'
+    PARTITION_1='1'
+    PARTITION_2='2'
+    ;;
+  *)
+    echo "No changes made, quitting."
+    exit 1
+    ;;
+esac
+
+
 ## Check tools and copy files
-tools_check () {
 echo "Checking tools..."
 
 ## Check if run with sudo or as root
@@ -57,92 +116,26 @@ cd /usr/local/aok || {
 ## crossystem fwid should show Veyron if it's a veyron board
 crossystem hwid && echo || echo "crossystem not found. OK."
 crossystem fwid && echo || echo "crossystem not found. OK."
-curl -V > /dev/null || { echo "curl not found. exiting." ; exit 1; }
+curl -V > /dev/null || { echo "curl not found. exiting."; exit 1; }
 ping -c 1 archlinuxarm.org > /dev/null \
   || echo "archlinuxarm.org not found. May use local data."
-md5sum --version > /dev/null || { echo "md5sum not found. exiting." ; exit 1; }
-umount -V > /dev/null || { echo "umount not found. exiting." ; exit 1; }
+md5sum --version > /dev/null || { echo "md5sum not found. exiting."; exit 1; }
+umount -V > /dev/null || { echo "umount not found. exiting."; exit 1; }
 fdisk -V
-cgpt add -h > /dev/null || { echo "cgpt not found. exiting." ; exit 1; }
-mkfs -V > /dev/null || { echo "mkfs not found. exiting." ; exit 1; }
-dd --version > /dev/null || { echo "dd not found. exiting." ; exit 1; }
+cgpt add -h > /dev/null || { echo "cgpt not found. exiting."; exit 1; }
+mkfs -V > /dev/null || { echo "mkfs not found. exiting."; exit 1; }
+dd --version > /dev/null || { echo "dd not found. exiting."; exit 1; }
 
 echo "Tools check complete."
-}
 
 
-## Test mirrors and hopefully create bestmirrors.txt
-test_mirrors () {
-echo "Testing mirrors..."
 
-## Create or reset the working mirrors list file, and set local mirror status
-echo -n > workingmirrors.txt.tmp
-LOCAL_MIRROR_SUCCESS=false
+## Installation process. Already working in /usr/local/ok
 
-## All local Arch Linux ARM mirrors, not the main load-balancing mirror:
-## https://archlinuxarm.org/about/mirrors
-## /etc/pacman.d/mirrorlist
-all_Mirrors=(au br2 dk de3 de de4 de5 de6 eu gr hu nl ru sg za tw ca.us nj.us fl.us il.us vn)
-
-## Try to download md5 file for each mirror, recording speeds
-for SUBDOMAIN in ${all_Mirrors[@]}; do
-
-  ## Download md5, and save Current Speed from curl progress meter
-  ## A higher number is better. Domains that fail will have a null value.
-  CURRENT_SPEED=$(curl --max-time 5 -LO \
-  ${SUBDOMAIN}.mirror.archlinuxarm.org/os/ArchLinuxARM-armv7-chromebook-latest.tar.gz.md5 \
-  2>&1 | grep $'\r100' | grep -o '[^ ]*$' || echo -n)
-
-  ## What if it's a bad md5 file, like a 404?
-  ## It should contain the filename, and be only 1 line
-  if [ $(grep ArchLinuxARM-armv7-chromebook-latest.tar.gz \
-      ArchLinuxARM-armv7-chromebook-latest.tar.gz.md5 | wc -l) -eq 1 ]; then
-
-    ## Save the working mirror to a text file, Format: Speed (tab) Mirror
-    if [ -n "$CURRENT_SPEED" ]; then
-      echo -e "${CURRENT_SPEED}\t${SUBDOMAIN}.mirror.archlinuxarm.org" \
-        | tee -a workingmirrors.txt.tmp
-      ## Save the best md5, and record success
-      cp -u ArchLinuxARM-armv7-chromebook-latest.tar.gz.md5 \
-          ArchLinuxARM-armv7-chromebook-latest.tar.gz.md5.tmp
-      MIRROR_SUCCESS=true
-      LOCAL_MIRROR_SUCCESS=true
-
-    ## If the md5 download failed, just report that.
-    else
-      echo -e "\t${SUBDOMAIN}.mirror.archlinuxarm.org failed completely"
-    fi
-
-  ## The md5 file appears to be invalid, so restore the good one if possible. 
-  else
-    echo -e "\t${SUBDOMAIN}.mirror.archlinuxarm.org did not provide the correct file (Likely 404)"
-    ## Restore the real (and best) md5 if one exists
-    cp ArchLinuxARM-armv7-chromebook-latest.tar.gz.md5.tmp \
-        ArchLinuxARM-armv7-chromebook-latest.tar.gz.md5 || echo -n
-  fi
-done
-
-## Create bestmirrors.txt if possible
-if [ "$LOCAL_MIRROR_SUCCESS" = true ]; then
-  echo
-  echo "These are your current best mirrors:"
-  echo -e "SPEED\tMIRROR"
-  ## Sort human readable reverse (highest first) to a sorted file
-  cat workingmirrors.txt.tmp | sort -hr | tee bestmirrors.txt
-else
-  echo
-  echo "No working local mirrors found."
-fi
-
-## Cleanup
-rm -f ArchLinuxARM-armv7-chromebook-latest.tar.gz.md5.tmp
-rm -f workingmirrors.txt.tmp
-echo "Mirrors testing complete."
-
-## Add a message just before a likely pause period
-echo "Do NOT click on pop-up messages!"
-}
-
+echo "Preparing files..."
+mkdir -p distro
+cd distro
+MIRROR_SUCCESS=false
 
 ## Offline function, try using local md5 or quit
 use_local_md5 () {
@@ -155,16 +148,8 @@ use_local_md5 () {
 }
 
 
-## Installation process. Already working in /usr/local/ok
-install_arch () {
-
-echo "Preparing files..."
-mkdir -p distro
-cd distro
-MIRROR_SUCCESS=false
-
 ## Check if Internet and DNS are working before testing any mirror
-if ping -c 1 archlinuxarm.org > /dev/null; then
+if [ $(ping -c 1 archlinuxarm.org > /dev/null) ]; then
 
   ## Allow 10 seconds to download the md5 from main mirror
   curl --max-time 10 -LO \
@@ -175,7 +160,76 @@ if ping -c 1 archlinuxarm.org > /dev/null; then
   } || echo -n
 
   ## Now test local mirrors
-  test_mirrors
+  ## Test mirrors and hopefully create bestmirrors.txt
+  echo "Testing mirrors..."
+
+  ## Create or reset the working mirrors list file, and set local mirror status
+  echo -n > workingmirrors.txt.tmp
+  LOCAL_MIRROR_SUCCESS=false
+
+  ## All local Arch Linux ARM mirrors, not the main load-balancing mirror:
+  ## https://archlinuxarm.org/about/mirrors
+  ## /etc/pacman.d/mirrorlist
+  all_Mirrors=(au br2 dk de3 de de4 de5 de6 eu gr hu nl ru sg za tw ca.us nj.us fl.us il.us vn)
+
+  ## Try to download md5 file for each mirror, recording speeds
+  for SUBDOMAIN in ${all_Mirrors[@]}; do
+
+    ## Download md5, and save Current Speed from curl progress meter
+    ## A higher number is better. Domains that fail will have a null value.
+    CURRENT_SPEED=$(curl --max-time 5 -LO \
+    ${SUBDOMAIN}.mirror.archlinuxarm.org/os/ArchLinuxARM-armv7-chromebook-latest.tar.gz.md5 \
+    2>&1 | grep $'\r100' | grep -o '[^ ]*$' || echo -n)
+
+    ## What if it's a bad md5 file, like a 404?
+    ## It should contain the filename, and be only 1 line
+    if [ $(grep ArchLinuxARM-armv7-chromebook-latest.tar.gz \
+        ArchLinuxARM-armv7-chromebook-latest.tar.gz.md5 | wc -l) -eq 1 ]; then
+
+      ## Save the working mirror to a text file, Format: Speed (tab) Mirror
+      if [ -n "$CURRENT_SPEED" ]; then
+        echo -e "${CURRENT_SPEED}\t${SUBDOMAIN}.mirror.archlinuxarm.org" \
+          | tee -a workingmirrors.txt.tmp
+        ## Save the best md5, and record success
+        cp -u ArchLinuxARM-armv7-chromebook-latest.tar.gz.md5 \
+            ArchLinuxARM-armv7-chromebook-latest.tar.gz.md5.tmp
+        MIRROR_SUCCESS=true
+        LOCAL_MIRROR_SUCCESS=true
+
+      ## If the md5 download failed, just report that.
+      else
+        echo -e "\t${SUBDOMAIN}.mirror.archlinuxarm.org failed completely"
+      fi
+
+    ## The md5 file appears to be invalid, so restore the good one if possible. 
+    else
+      echo -e "\t${SUBDOMAIN}.mirror.archlinuxarm.org did not provide the correct file (Likely 404)"
+      ## Restore the real (and best) md5 if one exists
+      cp ArchLinuxARM-armv7-chromebook-latest.tar.gz.md5.tmp \
+          ArchLinuxARM-armv7-chromebook-latest.tar.gz.md5 || echo -n
+    fi
+  done
+
+  ## Create bestmirrors.txt if possible
+  if [ "$LOCAL_MIRROR_SUCCESS" = true ]; then
+    echo
+    echo "These are your current best mirrors:"
+    echo -e "SPEED\tMIRROR"
+    ## Sort human readable reverse (highest first) to a sorted file
+    cat workingmirrors.txt.tmp | sort -hr | tee bestmirrors.txt
+  else
+    echo
+    echo "No working local mirrors found."
+  fi
+
+  ## Cleanup
+  rm -f ArchLinuxARM-armv7-chromebook-latest.tar.gz.md5.tmp
+  rm -f workingmirrors.txt.tmp
+  echo "Mirrors testing complete."
+
+  ## Add a message just before a likely pause period
+  echo "Do NOT click on pop-up messages!"
+
 
   if [ "$MIRROR_SUCCESS" = false ]; then
     echo "Cannot download latest md5: all mirrors failed."
@@ -186,10 +240,14 @@ else
     use_local_md5
 fi
 
+
+
+
+
 ## Check md5 against file even if it doesn't exist, or try downloading
 md5sum -c ArchLinuxARM-armv7-chromebook-latest.tar.gz.md5 --status || {
   echo "Attempting download..."
-  if ping -c 1 archlinuxarm.org > /dev/null; then
+  if [ $(ping -c 1 archlinuxarm.org > /dev/null) ]; then
 
     ## Get ready to try downloading from every working local mirror
     DOWNLOADED=false
@@ -295,7 +353,7 @@ partx -u ${DEVICE}
 mkdir -p rootfs
 mount ${DEVICE}${PARTITION_2} rootfs
 echo "Copying Filesystem..."
-## Ignore unimportant SCHILY.fflag related warnings
+## Ignore unimportant SCHILY.fflag warnings
 tar --warning=no-unknown-keyword -xf \
 distro/ArchLinuxARM-armv7-chromebook-latest.tar.gz -C rootfs --checkpoint=.500
 echo
@@ -438,74 +496,4 @@ case "$REBOOT" in
       echo "Rebooting..."
       reboot
       ;;
-esac
-}
-## End of install_arch function
-
-## Script starts here
-lsblk
-
-if [ $(uname -p | grep ARMv7) ]; then
-  echo
-  echo "Select what to ERASE and install Arch Linux on:"
-  echo 
-  echo "0) eMMC, erase ChromeOS  /dev/mmcblk0  Must be running from SD/USB already"
-  echo "1) SD Card               /dev/mmcblk1  4GB+ needed"
-  echo "a) USB Drive             /dev/sda      4GB+ needed. For compatible USB's."
-  echo "b) Second USB Drive      /dev/sdb      or VirtualBox SD Card"
-  echo "q) Quit"
-  echo
-else
-  echo
-  echo "Select what to ERASE and install Arch Linux on:"
-  echo 
-  echo "0) /dev/mmcblk0"
-  echo "1) /dev/mmcblk1"
-  echo "a) /dev/sda"
-  echo "b) /dev/sdb"
-  echo "c) /dev/sdc"
-  echo "q) Quit"
-  echo
-fi
-
-read -p "> " CHOICE
-case "$CHOICE" in
-  0)
-    DEVICE='/dev/mmcblk0'
-    PARTITION_1='p1'
-    PARTITION_2='p2'
-    tools_check
-    install_arch
-    ;;
-  1)
-    DEVICE='/dev/mmcblk1'
-    PARTITION_1='p1'
-    PARTITION_2='p2'
-    tools_check
-    install_arch
-    ;;
-  a)
-    DEVICE='/dev/sda'
-    PARTITION_1='1'
-    PARTITION_2='2'
-    tools_check
-    install_arch
-    ;;
-  b)
-    DEVICE='/dev/sdb'
-    PARTITION_1='1'
-    PARTITION_2='2'
-    tools_check
-    install_arch
-    ;;
-  c)
-    DEVICE='/dev/sdc'
-    PARTITION_1='1'
-    PARTITION_2='2'
-    tools_check
-    install_arch
-    ;;
-  *)
-    echo "No changes made, quitting."
-    ;;
 esac
