don't display hwid, fwid, or fdisk version

diff --git a/aokx b/aokx
--- a/aokx
+++ b/aokx
@@ -12,15 +12,15 @@ if [ "$EUID" != 0 ]; then
 fi
 
 ## Check for necessary tools
-crossystem hwid && echo || echo "crossystem not found. OK."
+# crossystem hwid && echo || echo "crossystem not found. OK."
 ## crossystem fwid should show Veyron if it's a veyron board
-crossystem fwid && echo || echo -n
+# crossystem fwid && echo || echo -n
 curl -V > /dev/null || { echo "curl not found. exiting."; exit 69; }
 ping -c 1 archlinuxarm.org > /dev/null \
   || echo "archlinuxarm.org not found. May use local data."
 md5sum --version > /dev/null || { echo "md5sum not found. exiting."; exit 70; }
 umount -V > /dev/null || { echo "umount not found. exiting."; exit 71; }
-fdisk -V
+fdisk -V > /dev/null || { echo "fdisk not found. exiting."; exit 81; }
 cgpt add -h > /dev/null || { echo "cgpt not found. exiting."; exit 72; }
 mkfs -V > /dev/null || { echo "mkfs not found. exiting."; exit 73; }
 dd --version > /dev/null || { echo "dd not found. exiting."; exit 74; }
